package main

const (
	categoryACM              = "ACM"
	categoryAPIGateway       = "API Gateway"
	categoryAthena           = "Athena"
	categoryAutoScaling      = "AutoScaling"
	categoryCloudFormation   = "CloudFormation"
	categoryCloudFront       = "CloudFront"
	categoryCloudTrail       = "CloudTrail"
	categoryCloudWatchLogs   = "CloudWatchLogs"
	categoryComprehend       = "Comprehend"
	categoryConfigService    = "ConfigService"
	categoryDMS              = "DMS"
	categoryDynamoDB         = "DynamoDB"
	categoryEC2              = "EC2"
	categoryECR              = "ECR"
	categoryEFS              = "EFS"
	categoryEKS              = "EKS"
	categoryElasticBeanstalk = "ElasticBeanstalk"
	categoryELB              = "ELB"
	categoryELBv2            = "ELBv2"
	categoryEMR              = "EMR"
	categoryES               = "ES"
	categoryFirehose         = "Firehose"
	categoryGlue             = "Glue"
	categoryGuardDuty        = "GuardDuty"
	categoryIAM              = "IAM"
	categoryKinesis          = "Kinesis"
	categoryKMS              = "KMS"
	categoryLambda           = "Lambda"
	categoryOrganizations    = "Organizations"
	categoryRDS              = "RDS"
	categoryRedshift         = "Redshift"
	categoryRoute53          = "Route53"
	categoryS3               = "S3"
	categorySageMaker        = "SageMaker"
	categorySES              = "SES"
	categoryShield           = "Shield"
	categorySNS              = "SNS"
	categorySQS              = "SQS"
	categorySSM              = "SSM"
	categoryTransfer         = "Transfer"
	categoryWorkspaces       = "Workspaces"
	categoryXRay             = "XRay"
)

var cloudSploitFindingMap = map[string]cloudSploitFindingInformation{
	categoryACM + "/acmCertificateExpiry":                 cloudSploitFindingInformation{Score: 6.0, ComplianceTag: []string{"pci"}},
	categoryACM + "/acmValidation":                        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAPIGateway + "/apigatewayWafEnabled":          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAthena + "/workgroupEncrypted":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAthena + "/workgroupEnforceConfiguration":     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAutoScaling + "/appTierAsgCloudwatchLogs":     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAutoScaling + "/appTierIamRole":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAutoScaling + "/asgActiveNotifications":       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAutoScaling + "/asgMissingELB":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAutoScaling + "/asgMissingSecurityGroups":     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAutoScaling + "/asgMultiAz":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAutoScaling + "/asgSuspendedProcesses":        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAutoScaling + "/elbHealthCheckActive":         cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAutoScaling + "/emptyASG":                     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAutoScaling + "/sameAzElb":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAutoScaling + "/webTierAsgAssociatedElb":      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAutoScaling + "/webTierAsgCloudwatchLogs":     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryAutoScaling + "/webTierIamRole":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryCloudFormation + "/plainTextParameters":       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryCloudFront + "/cloudfrontHttpsOnly":           cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa"}},
	categoryCloudFront + "/cloudfrontLoggingEnabled":      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryCloudFront + "/cloudfrontWafEnabled":          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryCloudFront + "/insecureProtocols":             cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryCloudFront + "/publicS3Origin":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa"}},
	categoryCloudFront + "/secureOrigin":                  cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa"}},
	categoryCloudTrail + "/cloudtrailBucketAccessLogging": cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci", "cis1", "cis"}},
	categoryCloudTrail + "/cloudtrailBucketDelete":        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa"}},
	categoryCloudTrail + "/cloudtrailBucketPrivate":       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"cis1", "cis"}},
	categoryCloudTrail + "/cloudtrailDataEvents":          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryCloudTrail + "/cloudtrailDeliveryFailing":     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryCloudTrail + "/cloudtrailEnabled":             cloudSploitFindingInformation{Score: 8.0, ComplianceTag: []string{"hipaa", "pci", "cis1", "cis"}},
	categoryCloudTrail + "/cloudtrailEncryption":          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"cis2", "cis"}},
	categoryCloudTrail + "/cloudtrailFileValidation":      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "cis2", "cis"}},
	categoryCloudTrail + "/cloudtrailObjectLock":          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryCloudTrail + "/cloudtrailS3Bucket":            cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryCloudTrail + "/cloudtrailToCloudwatch":        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"cis1", "cis"}},
	categoryCloudTrail + "/globalLoggingDuplicated":       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryCloudWatchLogs + "/monitoringMetrics":         cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"cis1", "cis"}},
	categoryComprehend + "/outputResultEncryption":        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryComprehend + "/volumeEncryption":              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryConfigService + "/configServiceEnabled":       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci", "cis1", "cis"}},
	categoryDMS + "/dmsEncryptionEnabled":                 cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa"}},
	categoryDynamoDB + "/daxClusterEncryption":            cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryDynamoDB + "/dynamoKmsEncryption":             cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/allowedCustomPorts":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/appTierInstanceIamRole":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/classicInstances":                     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryEC2 + "/crossVpcPublicPrivate":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci"}},
	categoryEC2 + "/defaultSecurityGroup":                 cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci", "cis2", "cis"}},
	categoryEC2 + "/defaultVpcExists":                     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/defaultVpcInUse":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/ebsEncryptedSnapshots":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa"}},
	categoryEC2 + "/ebsEncryptionEnabled":                 cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryEC2 + "/ebsOldSnapshots":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/ebsSnapshotLifecycle":                 cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/ebsSnapshotPrivate":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/ebsSnapshotPublic":                    cloudSploitFindingInformation{Score: 8.0, ComplianceTag: []string{}},
	categoryEC2 + "/ebsUnusedVolumes":                     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/ec2MetadataOptions":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/elasticIpLimit":                       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/encryptedAmi":                         cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa"}},
	categoryEC2 + "/excessiveSecurityGroups":              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci"}},
	categoryEC2 + "/flowLogsEnabled":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci", "cis2", "cis"}},
	categoryEC2 + "/instanceIamRole":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/instanceKeyBasedLogin":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/instanceLimit":                        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/instanceMaxCount":                     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/instanceVcpusLimit":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/launchWizardSecurityGroups":           cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/managedNatGateway":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/multipleSubnets":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/natMultiAz":                           cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openAllPortsProtocols":                cloudSploitFindingInformation{Score: 8.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryEC2 + "/openCIFS":                             cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openCustomPorts":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openDNS":                              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openDocker":                           cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openElasticsearch":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openFTP":                              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openHadoopNameNode":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openHadoopNameNodeWebUI":              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openKibana":                           cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openMySQL":                            cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openNetBIOS":                          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openOracle":                           cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openOracleAutoDataWarehouse":          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openPostgreSQL":                       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openRDP":                              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"cis1", "cis"}},
	categoryEC2 + "/openRPC":                              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openSalt":                             cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openSMBoTCP":                          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openSMTP":                             cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openSQLServer":                        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openSSH":                              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openTelnet":                           cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openVNCClient":                        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/openVNCServer":                        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/overlappingSecurityGroups":            cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/publicAmi":                            cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/publicIpAddress":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/securityGroupRfc1918":                 cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/subnetIpAvailability":                 cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/unassociatedElasticIp":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/unusedAmi":                            cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/unusedEni":                            cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/unusedVirtualPrivateGateway":          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/unusedVpcInternetGateways":            cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/vpcElasticIpLimit":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/vpcEndpointAcceptance":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/vpcEndpointExposed":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEC2 + "/webTierInstanceIamRole":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryECR + "/ecrRepositoryPolicy":                  cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryECR + "/ecrRepositoryTagImmutability":         cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEFS + "/efsCmkEncrypted":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEFS + "/efsEncryptionEnabled":                 cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryEKS + "/eksKubernetesVersion":                 cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEKS + "/eksLoggingEnabled":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEKS + "/eksPrivateEndpoint":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEKS + "/eksSecurityGroups":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryElasticBeanstalk + "/managedPlatformUpdates":  cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryELB + "/elbHttpsOnly":                         cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryELB + "/elbLoggingEnabled":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryELB + "/elbNoInstances":                       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryELB + "/insecureCiphers":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryELBv2 + "/elbv2DeletionProtection":            cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryELBv2 + "/elbv2HttpsOnly":                     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryELBv2 + "/elbv2LoggingEnabled":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryELBv2 + "/elbv2MinimumTargetInstances":        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryELBv2 + "/elbv2NlbListenerSecurity":           cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryELBv2 + "/elbv2NoInstances":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryELBv2 + "/elbv2WafEnabled":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEMR + "/emrClusterLogging":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEMR + "/emrEncryptionAtRest":                  cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryEMR + "/emrEncryptionInTransit":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryES + "/esAccessFromIps":                       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryES + "/esEncryptedDomain":                     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryES + "/esExposedDomain":                       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryES + "/esHttpsOnly":                           cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryES + "/esLoggingEnabled":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryES + "/esNodeToNodeEncryption":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryES + "/esPublicEndpoint":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryES + "/esRequireIAMAuth":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryES + "/esUpgradeAvailable":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryFirehose + "/firehoseEncrypted":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa"}},
	categoryGlue + "/bookmarkEncryptionEnabled":           cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryGuardDuty + "/guarddutyEnabled":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryGuardDuty + "/guarddutyMaster":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryIAM + "/accessKeysExtra":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryIAM + "/accessKeysLastUsed":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci", "cis1", "cis"}},
	categoryIAM + "/accessKeysRotated":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci", "cis1", "cis"}},
	categoryIAM + "/canaryKeysUsed":                       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryIAM + "/certificateExpiry":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryIAM + "/crossAccountMfaExtIdAccess":           cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryIAM + "/emptyGroups":                          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryIAM + "/groupInlinePolicies":                  cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryIAM + "/iamRoleLastUsed":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryIAM + "/iamRolePolicies":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryIAM + "/iamUserAdmins":                        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci"}},
	categoryIAM + "/iamUserNameRegex":                     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryIAM + "/iamUserUnauthorizedToEdit":            cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci"}},
	categoryIAM + "/maxPasswordAge":                       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci"}},
	categoryIAM + "/minPasswordLength":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci", "cis1", "cis"}},
	categoryIAM + "/noUserIamPolicies":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"cis1", "cis"}},
	categoryIAM + "/passwordExpiration":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci", "cis1", "cis"}},
	categoryIAM + "/passwordRequiresLowercase":            cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci", "cis1", "cis"}},
	categoryIAM + "/passwordRequiresNumbers":              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci", "cis1", "cis"}},
	categoryIAM + "/passwordRequiresSymbols":              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci", "cis1", "cis"}},
	categoryIAM + "/passwordRequiresUppercase":            cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci", "cis1", "cis"}},
	categoryIAM + "/passwordReusePrevention":              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci", "cis1", "cis"}},
	categoryIAM + "/rootAccessKeys":                       cloudSploitFindingInformation{Score: 8.0, ComplianceTag: []string{"hipaa", "cis1", "cis"}},
	categoryIAM + "/rootAccountInUse":                     cloudSploitFindingInformation{Score: 6.0, ComplianceTag: []string{"hipaa", "pci", "cis1", "cis"}},
	categoryIAM + "/rootHardwareMfa":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryIAM + "/rootMfaEnabled":                       cloudSploitFindingInformation{Score: 8.0, ComplianceTag: []string{"pci", "cis1", "cis"}},
	categoryIAM + "/rootSigningCertificate":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa"}},
	categoryIAM + "/sshKeysRotated":                       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryIAM + "/usersMfaEnabled":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci", "cis1", "cis"}},
	categoryIAM + "/usersPasswordAndKeys":                 cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryIAM + "/usersPasswordLastUsed":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci", "cis1", "cis"}},
	categoryKinesis + "/kinesisEncrypted":                 cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa"}},
	categoryKMS + "/kmsAppTierCmk":                        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryKMS + "/kmsDefaultKeyUsage":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci"}},
	categoryKMS + "/kmsKeyPolicy":                         cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryKMS + "/kmsKeyRotation":                       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci", "cis2", "cis"}},
	categoryKMS + "/kmsScheduledDeletion":                 cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryLambda + "/lambdaLogGroups":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryLambda + "/lambdaOldRuntimes":                 cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryLambda + "/lambdaPublicAccess":                cloudSploitFindingInformation{Score: 6.0, ComplianceTag: []string{}},
	categoryLambda + "/lambdaVpcConfig":                   cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryOrganizations + "/enableAllFeatures":          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryOrganizations + "/organizationInvite":         cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRDS + "/rdsAutomatedBackups":                  cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRDS + "/rdsCmkEncryptionEnabled":              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRDS + "/rdsEncryptionEnabled":                 cloudSploitFindingInformation{Score: 6.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryRDS + "/rdsLoggingEnabled":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRDS + "/rdsMinorVersionUpgrade":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRDS + "/rdsMultiAz":                           cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRDS + "/rdsPubliclyAccessible":                cloudSploitFindingInformation{Score: 8.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryRDS + "/rdsRestorable":                        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci"}},
	categoryRDS + "/rdsSnapshotEncryption":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRDS + "/rdsTransportEncryption":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRDS + "/sqlServerTLSVersion":                  cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRedshift + "/auditLoggingEnabled":             cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRedshift + "/redshiftAllowVersionUpgrade":     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRedshift + "/redshiftClusterCmkEncrypted":     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRedshift + "/redshiftEncryptionEnabled":       cloudSploitFindingInformation{Score: 6.0, ComplianceTag: []string{"hipaa"}},
	categoryRedshift + "/redshiftPubliclyAccessible":      cloudSploitFindingInformation{Score: 8.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryRedshift + "/redshiftSSLEnabled":              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRedshift + "/userActivityLoggingEnabled":      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRoute53 + "/danglingDnsRecords":               cloudSploitFindingInformation{Score: 6.0, ComplianceTag: []string{}},
	categoryRoute53 + "/domainAutoRenew":                  cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryRoute53 + "/domainExpiry":                     cloudSploitFindingInformation{Score: 8.0, ComplianceTag: []string{}},
	categoryRoute53 + "/domainTransferLock":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryS3 + "/bucketAllUsersAcl":                     cloudSploitFindingInformation{Score: 6.0, ComplianceTag: []string{"pci"}},
	categoryS3 + "/bucketAllUsersPolicy":                  cloudSploitFindingInformation{Score: 6.0, ComplianceTag: []string{"pci"}},
	categoryS3 + "/bucketEncryption":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryS3 + "/bucketEncryptionInTransit":             cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryS3 + "/bucketEnforceEncryption":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryS3 + "/bucketLogging":                         cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryS3 + "/bucketPublicAccessBlock":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryS3 + "/bucketSecureTransportEnabled":          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryS3 + "/bucketVersioning":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryS3 + "/bucketWebsiteEnabled":                  cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryS3 + "/s3Encryption":                          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categorySageMaker + "/notebookDataEncrypted":          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa"}},
	categorySageMaker + "/notebookDirectInternetAccess":   cloudSploitFindingInformation{Score: 6.0, ComplianceTag: []string{}},
	categorySES + "/dkimEnabled":                          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryShield + "/shieldAdvancedEnabled":             cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryShield + "/shieldEmergencyContacts":           cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryShield + "/shieldProtections":                 cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categorySNS + "/topicCmkEncrypted":                    cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categorySNS + "/topicEncrypted":                       cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categorySNS + "/topicPolicies":                        cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categorySQS + "/sqsCrossAccount":                      cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"pci"}},
	categorySQS + "/sqsEncrypted":                         cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci"}},
	categorySQS + "/sqsPublicAccess":                      cloudSploitFindingInformation{Score: 6.0, ComplianceTag: []string{}},
	categorySSM + "/ssmActiveOnAllInstances":              cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categorySSM + "/ssmAgentAutoUpdateEnabled":            cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categorySSM + "/ssmAgentLatestVersion":                cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categorySSM + "/ssmEncryptedParameters":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryTransfer + "/transferLoggingEnabled":          cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{"hipaa", "pci"}},
	categoryWorkspaces + "/workspacesIpAccessControl":     cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
	categoryXRay + "/xrayEncryptionEnabled":               cloudSploitFindingInformation{Score: 3.0, ComplianceTag: []string{}},
}

type cloudSploitFindingInformation struct {
	Score         float32
	ComplianceTag []string
}
