version: "3.8"

services:
  aws:
    networks:
      - aws
      - local-shared
    build:
      context: src/aws
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - PORT=9001
      - DB_MASTER_HOST=${DB_MASTER_HOST}
      - DB_MASTER_USER=${DB_MASTER_USER}
      - DB_MASTER_PASSWORD=${DB_MASTER_PASSWORD}
      - DB_SLAVE_HOST=${DB_SLAVE_HOST}
      - DB_SLAVE_USER=${DB_SLAVE_USER}
      - DB_SLAVE_PASSWORD=${DB_SLAVE_PASSWORD}
      - DB_PORT=3306
      - DB_SCHEMA=mimosa
      - DB_LOG_MODE=${DB_LOG_MODE}
    ports:
      - "9001:9001" # 本来docker-compose外にexposeする必要はない（Debug用）

  guard-duty:
    networks:
      - aws
      - local-shared
    build:
      context: src/guard-duty
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - QUEUE_NAME=${QUEUE_NAME}
      - QUEUE_URL=${QUEUE_URL}
      - FINDING_SVC_ADDR=${FINDING_SVC_ADDR}
    ports:
      - "9002"

networks:
  aws:
    driver: bridge
    attachable: true
  local-shared:
    external: true
    
