version: "3.8"

services:
  aws:
    networks:
      - aws
      - local-shared
    build:
      context: src/aws
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - PORT=9001
      - DB_MASTER_HOST=${DB_MASTER_HOST}
      - DB_MASTER_USER=${DB_MASTER_USER}
      - DB_MASTER_PASSWORD=${DB_MASTER_PASSWORD}
      - DB_SLAVE_HOST=${DB_SLAVE_HOST}
      - DB_SLAVE_USER=${DB_SLAVE_USER}
      - DB_SLAVE_PASSWORD=${DB_SLAVE_PASSWORD}
      - DB_PORT=3306
      - DB_SCHEMA=mimosa
      - DB_LOG_MODE=${DB_LOG_MODE}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - GUARD_DUTY_QUEUE_URL=${GUARD_DUTY_QUEUE_URL}
      - ACCESS_ANALYZER_QUEUE_URL=${ACCESS_ANALYZER_QUEUE_URL}
      - ADMIN_CHECKER_QUEUE_URL=${ADMIN_CHECKER_QUEUE_URL}
      - CLOUDSPLOIT_QUEUE_URL=${CLOUDSPLOIT_QUEUE_URL}
      - PORTSCAN_QUEUE_URL=${PORTSCAN_QUEUE_URL}
    ports:
      - "9001:9001"

  guard-duty:
    networks:
      - aws
      - local-shared
    build:
      context: src/guard-duty
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - DEBUG=true
      - AWS_REGION=${AWS_REGION}
      - MAX_NUMBER_OF_MESSAGE=${MAX_NUMBER_OF_MESSAGE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - GUARD_DUTY_QUEUE_NAME=${GUARD_DUTY_QUEUE_NAME}
      - GUARD_DUTY_QUEUE_URL=${GUARD_DUTY_QUEUE_URL}
      - FINDING_SVC_ADDR=${FINDING_SVC_ADDR}
      - ALERT_SVC_ADDR=${ALERT_SVC_ADDR}
      - AWS_SVC_ADDR=${AWS_SVC_ADDR}
    ports:
      - "9002"

  access-analyzer:
    networks:
      - aws
      - local-shared
    build:
      context: src/access-analyzer
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - DEBUG=true
      - AWS_REGION=${AWS_REGION}
      - MAX_NUMBER_OF_MESSAGE=${MAX_NUMBER_OF_MESSAGE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - ACCESS_ANALYZER_QUEUE_NAME=${ACCESS_ANALYZER_QUEUE_NAME}
      - ACCESS_ANALYZER_QUEUE_URL=${ACCESS_ANALYZER_QUEUE_URL}
      - FINDING_SVC_ADDR=${FINDING_SVC_ADDR}
      - ALERT_SVC_ADDR=${ALERT_SVC_ADDR}
      - AWS_SVC_ADDR=${AWS_SVC_ADDR}
    ports:
      - "9003"

  admin-checker:
    networks:
      - aws
      - local-shared
    build:
      context: src/admin-checker
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - DEBUG=true
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - ADMIN_CHECKER_QUEUE_NAME=${ADMIN_CHECKER_QUEUE_NAME}
      - ADMIN_CHECKER_QUEUE_URL=${ADMIN_CHECKER_QUEUE_URL}
      - FINDING_SVC_ADDR=${FINDING_SVC_ADDR}
      - ALERT_SVC_ADDR=${ALERT_SVC_ADDR}
      - AWS_SVC_ADDR=${AWS_SVC_ADDR}
    ports:
      - "9004"

  cloudsploit:
    networks:
      - aws
      - local-shared
    build:
      context: src/cloudsploit
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - DEBUG=true
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - CLOUDSPLOIT_QUEUE_NAME=${CLOUDSPLOIT_QUEUE_NAME}
      - CLOUDSPLOIT_QUEUE_URL=${CLOUDSPLOIT_QUEUE_URL}
      - FINDING_SVC_ADDR=${FINDING_SVC_ADDR}
      - ALERT_SVC_ADDR=${ALERT_SVC_ADDR}
      - AWS_SVC_ADDR=${AWS_SVC_ADDR}
    ports:
      - "9005"

  portscan:
    networks:
      - aws
      - local-shared
    build:
      context: src/portscan
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - DEBUG=true
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - MAX_NUMBER_OF_MESSAGE=${MAX_NUMBER_OF_MESSAGE}
      - PORTSCAN_QUEUE_NAME=${PORTSCAN_QUEUE_NAME}
      - PORTSCAN_QUEUE_URL=${PORTSCAN_QUEUE_URL}
      - FINDING_SVC_ADDR=${FINDING_SVC_ADDR}
      - ALERT_SVC_ADDR=${ALERT_SVC_ADDR}
      - AWS_SVC_ADDR=${AWS_SVC_ADDR}
      - SCAN_EXCLUDE_PORT_NUMBER=${SCAN_EXCLUDE_PORT_NUMBER}
    ports:
      - "9006"

  activity:
    networks:
      - aws
      - local-shared
    build:
      context: src/activity
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - PORT=9007
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SVC_ADDR=${AWS_SVC_ADDR}
    ports:
      - "9007:9007"

networks:
  aws:
    driver: bridge
    attachable: true
  local-shared:
    external: true
    
