// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: cloudtrail/service.proto

package cloudtrail

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _service_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on ListCloudTrailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListCloudTrailRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetProjectId() <= 0 {
		return ListCloudTrailRequestValidationError{
			field:  "ProjectId",
			reason: "value must be greater than 0",
		}
	}

	if m.GetAwsId() <= 0 {
		return ListCloudTrailRequestValidationError{
			field:  "AwsId",
			reason: "value must be greater than 0",
		}
	}

	if val := m.GetStartTime(); val < 0 || val > 253402268399 {
		return ListCloudTrailRequestValidationError{
			field:  "StartTime",
			reason: "value must be inside range [0, 253402268399]",
		}
	}

	if val := m.GetEndTime(); val < 0 || val > 253402268399 {
		return ListCloudTrailRequestValidationError{
			field:  "EndTime",
			reason: "value must be inside range [0, 253402268399]",
		}
	}

	// no validation rules for EventId

	// no validation rules for EventName

	// no validation rules for EventSource

	// no validation rules for ReadOnly

	// no validation rules for ResourceName

	// no validation rules for ResourceType

	// no validation rules for UserName

	return nil
}

// ListCloudTrailRequestValidationError is the validation error returned by
// ListCloudTrailRequest.Validate if the designated constraints aren't met.
type ListCloudTrailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCloudTrailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCloudTrailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCloudTrailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCloudTrailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCloudTrailRequestValidationError) ErrorName() string {
	return "ListCloudTrailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListCloudTrailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCloudTrailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCloudTrailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCloudTrailRequestValidationError{}

// Validate checks the field values on ListCloudTrailResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListCloudTrailResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetCloudtrail() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListCloudTrailResponseValidationError{
					field:  fmt.Sprintf("Cloudtrail[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListCloudTrailResponseValidationError is the validation error returned by
// ListCloudTrailResponse.Validate if the designated constraints aren't met.
type ListCloudTrailResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCloudTrailResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCloudTrailResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCloudTrailResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCloudTrailResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCloudTrailResponseValidationError) ErrorName() string {
	return "ListCloudTrailResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListCloudTrailResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCloudTrailResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCloudTrailResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCloudTrailResponseValidationError{}
