// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.12.1
// source: controller/service.proto

package controller

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ListAWSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId    uint32 `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AwsId        uint32 `protobuf:"varint,3,opt,name=aws_id,json=awsId,proto3" json:"aws_id,omitempty"`
	AwsAccountId string `protobuf:"bytes,4,opt,name=aws_account_id,json=awsAccountId,proto3" json:"aws_account_id,omitempty"`
}

func (x *ListAWSRequest) Reset() {
	*x = ListAWSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAWSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAWSRequest) ProtoMessage() {}

func (x *ListAWSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAWSRequest.ProtoReflect.Descriptor instead.
func (*ListAWSRequest) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListAWSRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListAWSRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListAWSRequest) GetAwsId() uint32 {
	if x != nil {
		return x.AwsId
	}
	return 0
}

func (x *ListAWSRequest) GetAwsAccountId() string {
	if x != nil {
		return x.AwsAccountId
	}
	return ""
}

type ListAWSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Aws []*AWS `protobuf:"bytes,1,rep,name=aws,proto3" json:"aws,omitempty"`
}

func (x *ListAWSResponse) Reset() {
	*x = ListAWSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAWSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAWSResponse) ProtoMessage() {}

func (x *ListAWSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAWSResponse.ProtoReflect.Descriptor instead.
func (*ListAWSResponse) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListAWSResponse) GetAws() []*AWS {
	if x != nil {
		return x.Aws
	}
	return nil
}

type PutAWSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32        `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Aws    *AWSForUpsert `protobuf:"bytes,2,opt,name=aws,proto3" json:"aws,omitempty"`
}

func (x *PutAWSRequest) Reset() {
	*x = PutAWSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutAWSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAWSRequest) ProtoMessage() {}

func (x *PutAWSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAWSRequest.ProtoReflect.Descriptor instead.
func (*PutAWSRequest) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{2}
}

func (x *PutAWSRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PutAWSRequest) GetAws() *AWSForUpsert {
	if x != nil {
		return x.Aws
	}
	return nil
}

type PutAWSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Aws *AWS `protobuf:"bytes,1,opt,name=aws,proto3" json:"aws,omitempty"`
}

func (x *PutAWSResponse) Reset() {
	*x = PutAWSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutAWSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAWSResponse) ProtoMessage() {}

func (x *PutAWSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAWSResponse.ProtoReflect.Descriptor instead.
func (*PutAWSResponse) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{3}
}

func (x *PutAWSResponse) GetAws() *AWS {
	if x != nil {
		return x.Aws
	}
	return nil
}

type DeleteAWSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AwsId  uint32 `protobuf:"varint,2,opt,name=aws_id,json=awsId,proto3" json:"aws_id,omitempty"`
}

func (x *DeleteAWSRequest) Reset() {
	*x = DeleteAWSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAWSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAWSRequest) ProtoMessage() {}

func (x *DeleteAWSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAWSRequest.ProtoReflect.Descriptor instead.
func (*DeleteAWSRequest) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAWSRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteAWSRequest) GetAwsId() uint32 {
	if x != nil {
		return x.AwsId
	}
	return 0
}

type ListAWSRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AwsRoleId uint32 `protobuf:"varint,2,opt,name=aws_role_id,json=awsRoleId,proto3" json:"aws_role_id,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Activated bool   `protobuf:"varint,4,opt,name=activated,proto3" json:"activated,omitempty"`
}

func (x *ListAWSRoleRequest) Reset() {
	*x = ListAWSRoleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAWSRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAWSRoleRequest) ProtoMessage() {}

func (x *ListAWSRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAWSRoleRequest.ProtoReflect.Descriptor instead.
func (*ListAWSRoleRequest) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListAWSRoleRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListAWSRoleRequest) GetAwsRoleId() uint32 {
	if x != nil {
		return x.AwsRoleId
	}
	return 0
}

func (x *ListAWSRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListAWSRoleRequest) GetActivated() bool {
	if x != nil {
		return x.Activated
	}
	return false
}

type ListAWSRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AwsRole []*AWSRole `protobuf:"bytes,1,rep,name=aws_role,json=awsRole,proto3" json:"aws_role,omitempty"`
}

func (x *ListAWSRoleResponse) Reset() {
	*x = ListAWSRoleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAWSRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAWSRoleResponse) ProtoMessage() {}

func (x *ListAWSRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAWSRoleResponse.ProtoReflect.Descriptor instead.
func (*ListAWSRoleResponse) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListAWSRoleResponse) GetAwsRole() []*AWSRole {
	if x != nil {
		return x.AwsRole
	}
	return nil
}

type PutAWSRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint32            `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AwsRole *AWSRoleForUpsert `protobuf:"bytes,2,opt,name=aws_role,json=awsRole,proto3" json:"aws_role,omitempty"`
}

func (x *PutAWSRoleRequest) Reset() {
	*x = PutAWSRoleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutAWSRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAWSRoleRequest) ProtoMessage() {}

func (x *PutAWSRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAWSRoleRequest.ProtoReflect.Descriptor instead.
func (*PutAWSRoleRequest) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{7}
}

func (x *PutAWSRoleRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PutAWSRoleRequest) GetAwsRole() *AWSRoleForUpsert {
	if x != nil {
		return x.AwsRole
	}
	return nil
}

type PutAWSRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AwsRole *AWSRole `protobuf:"bytes,1,opt,name=aws_role,json=awsRole,proto3" json:"aws_role,omitempty"`
}

func (x *PutAWSRoleResponse) Reset() {
	*x = PutAWSRoleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutAWSRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAWSRoleResponse) ProtoMessage() {}

func (x *PutAWSRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAWSRoleResponse.ProtoReflect.Descriptor instead.
func (*PutAWSRoleResponse) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{8}
}

func (x *PutAWSRoleResponse) GetAwsRole() *AWSRole {
	if x != nil {
		return x.AwsRole
	}
	return nil
}

type ListDataSourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AwsId      uint32 `protobuf:"varint,2,opt,name=aws_id,json=awsId,proto3" json:"aws_id,omitempty"`
	DataSource string `protobuf:"bytes,3,opt,name=data_source,json=dataSource,proto3" json:"data_source,omitempty"`
	ProjectId  uint32 `protobuf:"varint,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *ListDataSourceRequest) Reset() {
	*x = ListDataSourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataSourceRequest) ProtoMessage() {}

func (x *ListDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataSourceRequest.ProtoReflect.Descriptor instead.
func (*ListDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListDataSourceRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListDataSourceRequest) GetAwsId() uint32 {
	if x != nil {
		return x.AwsId
	}
	return 0
}

func (x *ListDataSourceRequest) GetDataSource() string {
	if x != nil {
		return x.DataSource
	}
	return ""
}

func (x *ListDataSourceRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type ListDataSourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataSource []*DataSource `protobuf:"bytes,1,rep,name=data_source,json=dataSource,proto3" json:"data_source,omitempty"`
}

func (x *ListDataSourceResponse) Reset() {
	*x = ListDataSourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDataSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataSourceResponse) ProtoMessage() {}

func (x *ListDataSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataSourceResponse.ProtoReflect.Descriptor instead.
func (*ListDataSourceResponse) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListDataSourceResponse) GetDataSource() []*DataSource {
	if x != nil {
		return x.DataSource
	}
	return nil
}

type AttachDataSourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId           uint32               `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AttachDataSource *DataSourceForAttach `protobuf:"bytes,2,opt,name=attach_data_source,json=attachDataSource,proto3" json:"attach_data_source,omitempty"`
}

func (x *AttachDataSourceRequest) Reset() {
	*x = AttachDataSourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDataSourceRequest) ProtoMessage() {}

func (x *AttachDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDataSourceRequest.ProtoReflect.Descriptor instead.
func (*AttachDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{11}
}

func (x *AttachDataSourceRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AttachDataSourceRequest) GetAttachDataSource() *DataSourceForAttach {
	if x != nil {
		return x.AttachDataSource
	}
	return nil
}

type AttachDataSourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataSource *DataSource `protobuf:"bytes,1,opt,name=data_source,json=dataSource,proto3" json:"data_source,omitempty"`
}

func (x *AttachDataSourceResponse) Reset() {
	*x = AttachDataSourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachDataSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDataSourceResponse) ProtoMessage() {}

func (x *AttachDataSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDataSourceResponse.ProtoReflect.Descriptor instead.
func (*AttachDataSourceResponse) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{12}
}

func (x *AttachDataSourceResponse) GetDataSource() *DataSource {
	if x != nil {
		return x.DataSource
	}
	return nil
}

type DetachDataSourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId          uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AwsId           uint32 `protobuf:"varint,2,opt,name=aws_id,json=awsId,proto3" json:"aws_id,omitempty"`
	AwsDataSourceId uint32 `protobuf:"varint,3,opt,name=aws_data_source_id,json=awsDataSourceId,proto3" json:"aws_data_source_id,omitempty"`
}

func (x *DetachDataSourceRequest) Reset() {
	*x = DetachDataSourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetachDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachDataSourceRequest) ProtoMessage() {}

func (x *DetachDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachDataSourceRequest.ProtoReflect.Descriptor instead.
func (*DetachDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{13}
}

func (x *DetachDataSourceRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DetachDataSourceRequest) GetAwsId() uint32 {
	if x != nil {
		return x.AwsId
	}
	return 0
}

func (x *DetachDataSourceRequest) GetAwsDataSourceId() uint32 {
	if x != nil {
		return x.AwsDataSourceId
	}
	return 0
}

type InvokeScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId          uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AwsId           uint32 `protobuf:"varint,2,opt,name=aws_id,json=awsId,proto3" json:"aws_id,omitempty"`
	AwsDataSourceId uint32 `protobuf:"varint,3,opt,name=aws_data_source_id,json=awsDataSourceId,proto3" json:"aws_data_source_id,omitempty"`
}

func (x *InvokeScanRequest) Reset() {
	*x = InvokeScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvokeScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeScanRequest) ProtoMessage() {}

func (x *InvokeScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeScanRequest.ProtoReflect.Descriptor instead.
func (*InvokeScanRequest) Descriptor() ([]byte, []int) {
	return file_controller_service_proto_rawDescGZIP(), []int{14}
}

func (x *InvokeScanRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InvokeScanRequest) GetAwsId() uint32 {
	if x != nil {
		return x.AwsId
	}
	return 0
}

func (x *InvokeScanRequest) GetAwsDataSourceId() uint32 {
	if x != nil {
		return x.AwsDataSourceId
	}
	return 0
}

var File_controller_service_proto protoreflect.FileDescriptor

var file_controller_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x77, 0x73, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x85, 0x01, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x57, 0x53, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x61,
	0x77, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x77, 0x73,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x61, 0x77, 0x73, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x77, 0x73, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x57, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x03, 0x61,
	0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x41, 0x57, 0x53, 0x52, 0x03, 0x61,
	0x77, 0x73, 0x22, 0x58, 0x0a, 0x0d, 0x50, 0x75, 0x74, 0x41, 0x57, 0x53, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x03,
	0x61, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x77, 0x73, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x41, 0x57, 0x53, 0x46, 0x6f,
	0x72, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x03, 0x61, 0x77, 0x73, 0x22, 0x37, 0x0a, 0x0e,
	0x50, 0x75, 0x74, 0x41, 0x57, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25,
	0x0a, 0x03, 0x61, 0x77, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x77,
	0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x41, 0x57, 0x53,
	0x52, 0x03, 0x61, 0x77, 0x73, 0x22, 0x42, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x57, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x77, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x61, 0x77, 0x73, 0x49, 0x64, 0x22, 0x7f, 0x0a, 0x12, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x57, 0x53, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x61, 0x77, 0x73, 0x5f,
	0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x61,
	0x77, 0x73, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x22, 0x49, 0x0a, 0x13, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x57, 0x53, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x32, 0x0a, 0x08, 0x61, 0x77, 0x73, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x41, 0x57, 0x53, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x07, 0x61, 0x77,
	0x73, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x69, 0x0a, 0x11, 0x50, 0x75, 0x74, 0x41, 0x57, 0x53, 0x52,
	0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x08, 0x61, 0x77, 0x73, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x41, 0x57, 0x53, 0x52, 0x6f, 0x6c, 0x65, 0x46, 0x6f,
	0x72, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x07, 0x61, 0x77, 0x73, 0x52, 0x6f, 0x6c, 0x65,
	0x22, 0x48, 0x0a, 0x12, 0x50, 0x75, 0x74, 0x41, 0x57, 0x53, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x61, 0x77, 0x73, 0x5f, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x41, 0x57, 0x53, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x07, 0x61, 0x77, 0x73, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x15, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x61, 0x77, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61,
	0x77, 0x73, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x0a, 0x64, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x17,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x51, 0x0a, 0x12, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61,
	0x77, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x6f, 0x72, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x52, 0x10, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x22, 0x57, 0x0a, 0x18, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x76, 0x0a, 0x17,
	0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x15, 0x0a, 0x06, 0x61, 0x77, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x61, 0x77, 0x73, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x12, 0x61, 0x77, 0x73, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0f, 0x61, 0x77, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x64, 0x22, 0x70, 0x0a, 0x11, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x53, 0x63,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x77, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x61, 0x77, 0x73, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x12, 0x61, 0x77, 0x73,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x61, 0x77, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x32, 0xfb, 0x05, 0x0a, 0x0a, 0x41, 0x57, 0x53, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x57, 0x53,
	0x12, 0x1e, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x57, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x57, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x47, 0x0a, 0x06, 0x50, 0x75, 0x74, 0x41, 0x57, 0x53, 0x12, 0x1d, 0x2e, 0x61, 0x77,
	0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x74,
	0x41, 0x57, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x77, 0x73,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x74, 0x41,
	0x57, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x09, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x57, 0x53, 0x12, 0x20, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x57, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x56, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x57, 0x53, 0x52, 0x6f, 0x6c, 0x65,
	0x12, 0x22, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x57, 0x53, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x57, 0x53, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0a, 0x50, 0x75, 0x74,
	0x41, 0x57, 0x53, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x21, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x74, 0x41, 0x57, 0x53, 0x52,
	0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x77, 0x73,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x74, 0x41,
	0x57, 0x53, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f,
	0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x25, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x65, 0x0a, 0x10, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x27, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61,
	0x77, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x27, 0x2e, 0x61, 0x77, 0x73,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x74, 0x61,
	0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x47, 0x0a, 0x0a, 0x49,
	0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x21, 0x2e, 0x61, 0x77, 0x73, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x6b,
	0x65, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x43, 0x79, 0x62, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x69,
	0x6d, 0x6f, 0x73, 0x61, 0x2d, 0x61, 0x77, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_controller_service_proto_rawDescOnce sync.Once
	file_controller_service_proto_rawDescData = file_controller_service_proto_rawDesc
)

func file_controller_service_proto_rawDescGZIP() []byte {
	file_controller_service_proto_rawDescOnce.Do(func() {
		file_controller_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_controller_service_proto_rawDescData)
	})
	return file_controller_service_proto_rawDescData
}

var file_controller_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_controller_service_proto_goTypes = []interface{}{
	(*ListAWSRequest)(nil),           // 0: aws.controller.ListAWSRequest
	(*ListAWSResponse)(nil),          // 1: aws.controller.ListAWSResponse
	(*PutAWSRequest)(nil),            // 2: aws.controller.PutAWSRequest
	(*PutAWSResponse)(nil),           // 3: aws.controller.PutAWSResponse
	(*DeleteAWSRequest)(nil),         // 4: aws.controller.DeleteAWSRequest
	(*ListAWSRoleRequest)(nil),       // 5: aws.controller.ListAWSRoleRequest
	(*ListAWSRoleResponse)(nil),      // 6: aws.controller.ListAWSRoleResponse
	(*PutAWSRoleRequest)(nil),        // 7: aws.controller.PutAWSRoleRequest
	(*PutAWSRoleResponse)(nil),       // 8: aws.controller.PutAWSRoleResponse
	(*ListDataSourceRequest)(nil),    // 9: aws.controller.ListDataSourceRequest
	(*ListDataSourceResponse)(nil),   // 10: aws.controller.ListDataSourceResponse
	(*AttachDataSourceRequest)(nil),  // 11: aws.controller.AttachDataSourceRequest
	(*AttachDataSourceResponse)(nil), // 12: aws.controller.AttachDataSourceResponse
	(*DetachDataSourceRequest)(nil),  // 13: aws.controller.DetachDataSourceRequest
	(*InvokeScanRequest)(nil),        // 14: aws.controller.InvokeScanRequest
	(*AWS)(nil),                      // 15: aws.controller.AWS
	(*AWSForUpsert)(nil),             // 16: aws.controller.AWSForUpsert
	(*AWSRole)(nil),                  // 17: aws.controller.AWSRole
	(*AWSRoleForUpsert)(nil),         // 18: aws.controller.AWSRoleForUpsert
	(*DataSource)(nil),               // 19: aws.controller.DataSource
	(*DataSourceForAttach)(nil),      // 20: aws.controller.DataSourceForAttach
	(*empty.Empty)(nil),              // 21: google.protobuf.Empty
}
var file_controller_service_proto_depIdxs = []int32{
	15, // 0: aws.controller.ListAWSResponse.aws:type_name -> aws.controller.AWS
	16, // 1: aws.controller.PutAWSRequest.aws:type_name -> aws.controller.AWSForUpsert
	15, // 2: aws.controller.PutAWSResponse.aws:type_name -> aws.controller.AWS
	17, // 3: aws.controller.ListAWSRoleResponse.aws_role:type_name -> aws.controller.AWSRole
	18, // 4: aws.controller.PutAWSRoleRequest.aws_role:type_name -> aws.controller.AWSRoleForUpsert
	17, // 5: aws.controller.PutAWSRoleResponse.aws_role:type_name -> aws.controller.AWSRole
	19, // 6: aws.controller.ListDataSourceResponse.data_source:type_name -> aws.controller.DataSource
	20, // 7: aws.controller.AttachDataSourceRequest.attach_data_source:type_name -> aws.controller.DataSourceForAttach
	19, // 8: aws.controller.AttachDataSourceResponse.data_source:type_name -> aws.controller.DataSource
	0,  // 9: aws.controller.AWSService.ListAWS:input_type -> aws.controller.ListAWSRequest
	2,  // 10: aws.controller.AWSService.PutAWS:input_type -> aws.controller.PutAWSRequest
	4,  // 11: aws.controller.AWSService.DeleteAWS:input_type -> aws.controller.DeleteAWSRequest
	5,  // 12: aws.controller.AWSService.ListAWSRole:input_type -> aws.controller.ListAWSRoleRequest
	7,  // 13: aws.controller.AWSService.PutAWSRole:input_type -> aws.controller.PutAWSRoleRequest
	9,  // 14: aws.controller.AWSService.ListDataSource:input_type -> aws.controller.ListDataSourceRequest
	11, // 15: aws.controller.AWSService.AttachDataSource:input_type -> aws.controller.AttachDataSourceRequest
	13, // 16: aws.controller.AWSService.DetachDataSource:input_type -> aws.controller.DetachDataSourceRequest
	14, // 17: aws.controller.AWSService.InvokeScan:input_type -> aws.controller.InvokeScanRequest
	1,  // 18: aws.controller.AWSService.ListAWS:output_type -> aws.controller.ListAWSResponse
	3,  // 19: aws.controller.AWSService.PutAWS:output_type -> aws.controller.PutAWSResponse
	21, // 20: aws.controller.AWSService.DeleteAWS:output_type -> google.protobuf.Empty
	6,  // 21: aws.controller.AWSService.ListAWSRole:output_type -> aws.controller.ListAWSRoleResponse
	8,  // 22: aws.controller.AWSService.PutAWSRole:output_type -> aws.controller.PutAWSRoleResponse
	10, // 23: aws.controller.AWSService.ListDataSource:output_type -> aws.controller.ListDataSourceResponse
	12, // 24: aws.controller.AWSService.AttachDataSource:output_type -> aws.controller.AttachDataSourceResponse
	21, // 25: aws.controller.AWSService.DetachDataSource:output_type -> google.protobuf.Empty
	21, // 26: aws.controller.AWSService.InvokeScan:output_type -> google.protobuf.Empty
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_controller_service_proto_init() }
func file_controller_service_proto_init() {
	if File_controller_service_proto != nil {
		return
	}
	file_controller_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_controller_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAWSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAWSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutAWSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutAWSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAWSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAWSRoleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAWSRoleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutAWSRoleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutAWSRoleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDataSourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDataSourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachDataSourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachDataSourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetachDataSourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvokeScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_controller_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_service_proto_goTypes,
		DependencyIndexes: file_controller_service_proto_depIdxs,
		MessageInfos:      file_controller_service_proto_msgTypes,
	}.Build()
	File_controller_service_proto = out.File
	file_controller_service_proto_rawDesc = nil
	file_controller_service_proto_goTypes = nil
	file_controller_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AWSServiceClient is the client API for AWSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AWSServiceClient interface {
	// AWS
	ListAWS(ctx context.Context, in *ListAWSRequest, opts ...grpc.CallOption) (*ListAWSResponse, error)
	PutAWS(ctx context.Context, in *PutAWSRequest, opts ...grpc.CallOption) (*PutAWSResponse, error)
	DeleteAWS(ctx context.Context, in *DeleteAWSRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// AWS Role
	ListAWSRole(ctx context.Context, in *ListAWSRoleRequest, opts ...grpc.CallOption) (*ListAWSRoleResponse, error)
	PutAWSRole(ctx context.Context, in *PutAWSRoleRequest, opts ...grpc.CallOption) (*PutAWSRoleResponse, error)
	// AWS DataSource
	ListDataSource(ctx context.Context, in *ListDataSourceRequest, opts ...grpc.CallOption) (*ListDataSourceResponse, error)
	AttachDataSource(ctx context.Context, in *AttachDataSourceRequest, opts ...grpc.CallOption) (*AttachDataSourceResponse, error)
	DetachDataSource(ctx context.Context, in *DetachDataSourceRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Scan
	InvokeScan(ctx context.Context, in *InvokeScanRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type aWSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAWSServiceClient(cc grpc.ClientConnInterface) AWSServiceClient {
	return &aWSServiceClient{cc}
}

func (c *aWSServiceClient) ListAWS(ctx context.Context, in *ListAWSRequest, opts ...grpc.CallOption) (*ListAWSResponse, error) {
	out := new(ListAWSResponse)
	err := c.cc.Invoke(ctx, "/aws.controller.AWSService/ListAWS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSServiceClient) PutAWS(ctx context.Context, in *PutAWSRequest, opts ...grpc.CallOption) (*PutAWSResponse, error) {
	out := new(PutAWSResponse)
	err := c.cc.Invoke(ctx, "/aws.controller.AWSService/PutAWS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSServiceClient) DeleteAWS(ctx context.Context, in *DeleteAWSRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/aws.controller.AWSService/DeleteAWS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSServiceClient) ListAWSRole(ctx context.Context, in *ListAWSRoleRequest, opts ...grpc.CallOption) (*ListAWSRoleResponse, error) {
	out := new(ListAWSRoleResponse)
	err := c.cc.Invoke(ctx, "/aws.controller.AWSService/ListAWSRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSServiceClient) PutAWSRole(ctx context.Context, in *PutAWSRoleRequest, opts ...grpc.CallOption) (*PutAWSRoleResponse, error) {
	out := new(PutAWSRoleResponse)
	err := c.cc.Invoke(ctx, "/aws.controller.AWSService/PutAWSRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSServiceClient) ListDataSource(ctx context.Context, in *ListDataSourceRequest, opts ...grpc.CallOption) (*ListDataSourceResponse, error) {
	out := new(ListDataSourceResponse)
	err := c.cc.Invoke(ctx, "/aws.controller.AWSService/ListDataSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSServiceClient) AttachDataSource(ctx context.Context, in *AttachDataSourceRequest, opts ...grpc.CallOption) (*AttachDataSourceResponse, error) {
	out := new(AttachDataSourceResponse)
	err := c.cc.Invoke(ctx, "/aws.controller.AWSService/AttachDataSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSServiceClient) DetachDataSource(ctx context.Context, in *DetachDataSourceRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/aws.controller.AWSService/DetachDataSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSServiceClient) InvokeScan(ctx context.Context, in *InvokeScanRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/aws.controller.AWSService/InvokeScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AWSServiceServer is the server API for AWSService service.
type AWSServiceServer interface {
	// AWS
	ListAWS(context.Context, *ListAWSRequest) (*ListAWSResponse, error)
	PutAWS(context.Context, *PutAWSRequest) (*PutAWSResponse, error)
	DeleteAWS(context.Context, *DeleteAWSRequest) (*empty.Empty, error)
	// AWS Role
	ListAWSRole(context.Context, *ListAWSRoleRequest) (*ListAWSRoleResponse, error)
	PutAWSRole(context.Context, *PutAWSRoleRequest) (*PutAWSRoleResponse, error)
	// AWS DataSource
	ListDataSource(context.Context, *ListDataSourceRequest) (*ListDataSourceResponse, error)
	AttachDataSource(context.Context, *AttachDataSourceRequest) (*AttachDataSourceResponse, error)
	DetachDataSource(context.Context, *DetachDataSourceRequest) (*empty.Empty, error)
	// Scan
	InvokeScan(context.Context, *InvokeScanRequest) (*empty.Empty, error)
}

// UnimplementedAWSServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAWSServiceServer struct {
}

func (*UnimplementedAWSServiceServer) ListAWS(context.Context, *ListAWSRequest) (*ListAWSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAWS not implemented")
}
func (*UnimplementedAWSServiceServer) PutAWS(context.Context, *PutAWSRequest) (*PutAWSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutAWS not implemented")
}
func (*UnimplementedAWSServiceServer) DeleteAWS(context.Context, *DeleteAWSRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAWS not implemented")
}
func (*UnimplementedAWSServiceServer) ListAWSRole(context.Context, *ListAWSRoleRequest) (*ListAWSRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAWSRole not implemented")
}
func (*UnimplementedAWSServiceServer) PutAWSRole(context.Context, *PutAWSRoleRequest) (*PutAWSRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutAWSRole not implemented")
}
func (*UnimplementedAWSServiceServer) ListDataSource(context.Context, *ListDataSourceRequest) (*ListDataSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDataSource not implemented")
}
func (*UnimplementedAWSServiceServer) AttachDataSource(context.Context, *AttachDataSourceRequest) (*AttachDataSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachDataSource not implemented")
}
func (*UnimplementedAWSServiceServer) DetachDataSource(context.Context, *DetachDataSourceRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetachDataSource not implemented")
}
func (*UnimplementedAWSServiceServer) InvokeScan(context.Context, *InvokeScanRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeScan not implemented")
}

func RegisterAWSServiceServer(s *grpc.Server, srv AWSServiceServer) {
	s.RegisterService(&_AWSService_serviceDesc, srv)
}

func _AWSService_ListAWS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAWSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSServiceServer).ListAWS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aws.controller.AWSService/ListAWS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSServiceServer).ListAWS(ctx, req.(*ListAWSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSService_PutAWS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAWSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSServiceServer).PutAWS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aws.controller.AWSService/PutAWS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSServiceServer).PutAWS(ctx, req.(*PutAWSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSService_DeleteAWS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAWSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSServiceServer).DeleteAWS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aws.controller.AWSService/DeleteAWS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSServiceServer).DeleteAWS(ctx, req.(*DeleteAWSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSService_ListAWSRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAWSRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSServiceServer).ListAWSRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aws.controller.AWSService/ListAWSRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSServiceServer).ListAWSRole(ctx, req.(*ListAWSRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSService_PutAWSRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAWSRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSServiceServer).PutAWSRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aws.controller.AWSService/PutAWSRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSServiceServer).PutAWSRole(ctx, req.(*PutAWSRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSService_ListDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSServiceServer).ListDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aws.controller.AWSService/ListDataSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSServiceServer).ListDataSource(ctx, req.(*ListDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSService_AttachDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSServiceServer).AttachDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aws.controller.AWSService/AttachDataSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSServiceServer).AttachDataSource(ctx, req.(*AttachDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSService_DetachDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSServiceServer).DetachDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aws.controller.AWSService/DetachDataSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSServiceServer).DetachDataSource(ctx, req.(*DetachDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSService_InvokeScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSServiceServer).InvokeScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aws.controller.AWSService/InvokeScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSServiceServer).InvokeScan(ctx, req.(*InvokeScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AWSService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aws.controller.AWSService",
	HandlerType: (*AWSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAWS",
			Handler:    _AWSService_ListAWS_Handler,
		},
		{
			MethodName: "PutAWS",
			Handler:    _AWSService_PutAWS_Handler,
		},
		{
			MethodName: "DeleteAWS",
			Handler:    _AWSService_DeleteAWS_Handler,
		},
		{
			MethodName: "ListAWSRole",
			Handler:    _AWSService_ListAWSRole_Handler,
		},
		{
			MethodName: "PutAWSRole",
			Handler:    _AWSService_PutAWSRole_Handler,
		},
		{
			MethodName: "ListDataSource",
			Handler:    _AWSService_ListDataSource_Handler,
		},
		{
			MethodName: "AttachDataSource",
			Handler:    _AWSService_AttachDataSource_Handler,
		},
		{
			MethodName: "DetachDataSource",
			Handler:    _AWSService_DetachDataSource_Handler,
		},
		{
			MethodName: "InvokeScan",
			Handler:    _AWSService_InvokeScan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller/service.proto",
}
