name: Build and Tag Container for PR AWS

permissions:
  contents: read
  checks: write
  statuses: write

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build-pr-aws:
    uses: ca-risken/.github/.github/workflows/build-pr.yml@main
    with:
      runs_on: codebuild-mimosa-aws-pr-ruuner-${{ github.run_id }}-${{ github.run_attempt }}
      install_go_version: "1.21.3"
      golangci_lint_version: "v1.55.2"
      image_prefix: "risken-aws"
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
